### ISSUE TITLE
Can not forward property in preview.5

### ISSUE THREAD

**Issue by serjek** [haxetink/tink_lang#29]
`lix use haxe 4.0.0-preview.5
`

`
@:forward(length) var a:Array<Int> = [1];
`
Will emit following error upon compilation: length: Custom property accessor is no longer supported, please use get.

**Comment by back2dos** [comment]
Should be fixed by HEAD of tink_macro.

**Comment by JoeCreates** [comment]
@back2dos This is still broken for (at least) @:property and @:readonly.

https://github.com/haxetink/tink_lang/blob/master/src/tink/lang/sugar/PropertyNotation.hx#L27

I made a PR.
